INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (1, '014 Boyle Hollow Suite 258\nEast Justus, NM 87723-2', '84405');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (2, '196 Brown Fall Apt. 645\nMaxstad, KS 13422-6334', '59873');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (3, '935 Labadie Lodge\nHellerside, NJ 10272-6700', '60909');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (4, '5784 Skiles Turnpike Suite 470\nHendersonhaven, NE ', '16538');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (5, '35598 Connelly Mall Apt. 351\nRyleyland, OR 74566', '98271');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (6, '092 Gerlach Track Apt. 632\nPurdybury, AK 41835-878', '92223');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (7, '3925 Amanda Junction Suite 478\nPort Lauriane, NY 6', '7355');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (8, '698 Brian Mills Apt. 831\nThompsonside, MT 56204-03', '98349');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (9, '400 Florian Plaza\nSydnitown, NV 93185-6155', '907');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (10, '09321 Orn Hill Suite 661\nEast Waino, MO 67561-8416', '44264');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (11, '037 Micaela Keys\nBrandimouth, MI 21037', '8372');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (12, '939 Paris Port\nWest Percy, NY 55607', '43011');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (13, '183 Domenic Lodge\nEast Ramiroview, OR 01395', '35996');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (14, '454 Lubowitz Spurs Suite 712\nTrompchester, WY 5392', '1516');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (15, '28997 Watson Orchard\nNew Lempiview, VA 28309-1290', '39106');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (16, '959 Beahan Keys Apt. 303\nLake Anita, FL 11919', '90935');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (17, '0527 Claudie Lodge Apt. 364\nEast Nelda, WY 73961-1', '38341');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (18, '825 Wilfred Vista Suite 668\nKutchton, VA 97568', '41116');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (19, '3393 Schowalter Highway\nWest Payton, KY 45567', '39212');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (20, '19194 Kristy Bridge Suite 120\nPfefferville, IL 768', '14468');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (21, '121 Breitenberg Rue Apt. 613\nJonesmouth, CA 53958-', '23493');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (22, '60082 Domenica Overpass\nNew Hollymouth, NY 27564-7', '94291');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (23, '8455 Pacocha Lane\nPort Kaseyton, SC 48700-6672', '28011');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (24, '46947 Destiney Trace\nEast Nathanaelstad, AK 19610-', '98287');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (25, '92636 Wolff Freeway\nLarkinstad, GA 06922', '6182');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (26, '1149 Reid Spring\nSouth Sadyeside, CT 30852', '96225');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (27, '7809 Hintz Hills\nPort Imelda, NJ 08293-3196', '30981');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (28, '440 Hane Square\nWest Kelsie, AK 82807-0865', '68439');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (29, '351 Derek Point Suite 348\nWest Carmel, KS 65866', '38418');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (30, '869 Tomas Fords\nCasperhaven, IN 21360', '48195');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (31, '80728 Mills Green Apt. 484\nKuhlmanberg, AL 39801', '3458');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (32, '62577 Luettgen Port\nSouth Rasheed, DC 31166', '67792');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (33, '8689 Auer Meadows\nNorth Ladariusmouth, OK 81842-69', '86136');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (34, '6735 Christine Club\nSophiashire, RI 26042', '73297');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (35, '953 Claudia Plains\nGiannishire, SD 90550', '12222');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (36, '7212 Balistreri Row Suite 070\nWest Reymundoport, M', '50237');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (37, '355 Bashirian Knoll Apt. 024\nStantonfurt, UT 45812', '3391');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (38, '128 Gino Junction\nNorth Artchester, NY 94977', '24536');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (39, '66797 Batz Ville Suite 705\nHowardton, AZ 39683-769', '39470');
INSERT INTO `ATMs` (`id`, `address`, `balance`) VALUES (40, '510 Colten Circles\nDurganshire, NV 19098-8259', '97882');

INSERT INTO `bank`.`issuers` (`id`, `issuerName`) VALUES ('1', 'Visa');
INSERT INTO `bank`.`issuers` (`id`, `issuerName`) VALUES ('2', 'MasterCard');
INSERT INTO `bank`.`issuers` (`id`, `issuerName`) VALUES ('3', 'American Express');
INSERT INTO `bank`.`issuers` (`id`, `issuerName`) VALUES ('4', 'Chase');
INSERT INTO `bank`.`issuers` (`id`, `issuerName`) VALUES ('5', 'Discover');
INSERT INTO `bank`.`issuers` (`id`, `issuerName`) VALUES ('6', 'Citibank');
INSERT INTO `bank`.`issuers` (`id`, `issuerName`) VALUES ('7', 'Capital One');

INSERT INTO `bank`.`currencies` (`id`, `triple_code`, `exchange_rate`) VALUES ('1', 'EGP', '1');
INSERT INTO `bank`.`currencies` (`id`, `triple_code`, `exchange_rate`) VALUES ('2', 'USD', '17.91');
INSERT INTO `bank`.`currencies` (`id`, `triple_code`, `exchange_rate`) VALUES ('3', 'EUR', '20.45');
INSERT INTO `bank`.`currencies` (`id`, `triple_code`, `exchange_rate`) VALUES ('4', 'JPY', '0.16');
INSERT INTO `bank`.`currencies` (`id`, `triple_code`, `exchange_rate`) VALUES ('5', 'GBP', '22.71');
INSERT INTO `bank`.`currencies` (`id`, `triple_code`, `exchange_rate`) VALUES ('6', 'CHF', '18.09');
INSERT INTO `bank`.`currencies` (`id`, `triple_code`, `exchange_rate`) VALUES ('7', 'CAD', '13.23');
INSERT INTO `bank`.`currencies` (`id`, `triple_code`, `exchange_rate`) VALUES ('8', 'AUD', '12.71');

INSERT INTO `bank`.`sub_accounts` (`id`, `acc_name`, `description`, `interest_rate`, `interest_interval`) VALUES ('1', 'Checking Accounts', 'user has a checkbook and ATM card', '0.05', '1');
INSERT INTO `bank`.`sub_accounts` (`id`, `acc_name`, `description`, `interest_rate`, `interest_interval`) VALUES ('2', 'Dividend Checking Accounts', 'a combination of checking and savings accounts', '0.10', '3');
INSERT INTO `bank`.`sub_accounts` (`id`, `acc_name`, `description`, `interest_rate`, `interest_interval`) VALUES ('3', 'Savings Accounts', 'encouraged to save your money for a period of time', '0.25', '12');
INSERT INTO `bank`.`sub_accounts` (`id`, `acc_name`, `description`, `interest_rate`, `interest_interval`) VALUES ('4', 'Current Accounts', 'write checks to withdraw and deposit into that account', '0.07', '2');

INSERT INTO `bank`.`branches` (`SWIFT`, `b_name`, `phone_number`, `postal_code`, `address`, `city`, `opening`) VALUES ('CAIEGP', 'CairoBranch', '0222588933', '12123', 'Cairo', 'Cairo', '1974-11-02');
INSERT INTO `bank`.`branches` (`SWIFT`, `b_name`, `phone_number`, `postal_code`, `address`, `city`, `opening`) VALUES ('ALXEGP', 'AlexandriaBranch', '0358434674', '42365', 'Alexandria', 'Alexandria', '1999-12-16');
INSERT INTO `bank`.`branches` (`SWIFT`, `b_name`, `phone_number`, `postal_code`, `address`, `city`, `opening`) VALUES ('GZAEGP', 'GizaBranch', '0233648756', '75423', 'Giza', 'Giza', '2007-02-01');

INSERT INTO `bank`.`departments` (`id`, `d_name`) VALUES ('1', 'Customer Service Depatment');
INSERT INTO `bank`.`departments` (`id`, `d_name`) VALUES ('2', 'Financial Depatment');
INSERT INTO `bank`.`departments` (`id`, `d_name`) VALUES ('3', 'Inspection Department');

INSERT INTO `bank`.`department_branch` (`branch_swift`, `dept_id`) VALUES ('ALXEGP', '1');
INSERT INTO `bank`.`department_branch` (`branch_swift`, `dept_id`) VALUES ('ALXEGP', '2');
INSERT INTO `bank`.`department_branch` (`branch_swift`, `dept_id`) VALUES ('ALXEGP', '3');
INSERT INTO `bank`.`department_branch` (`branch_swift`, `dept_id`) VALUES ('CAIEGP', '1');
INSERT INTO `bank`.`department_branch` (`branch_swift`, `dept_id`) VALUES ('CAIEGP', '2');
INSERT INTO `bank`.`department_branch` (`branch_swift`, `dept_id`) VALUES ('CAIEGP', '3');
INSERT INTO `bank`.`department_branch` (`branch_swift`, `dept_id`) VALUES ('GZAEGP', '1');
INSERT INTO `bank`.`department_branch` (`branch_swift`, `dept_id`) VALUES ('GZAEGP', '2');
INSERT INTO `bank`.`department_branch` (`branch_swift`, `dept_id`) VALUES ('GZAEGP', '3');

INSERT INTO `bank`.`roles` (`id`, `r_name`, `dept_id`) VALUES ('21', 'Manager', '3');
INSERT INTO `bank`.`roles` (`id`, `r_name`, `dept_id`) VALUES ('22', 'Teller', '1');
INSERT INTO `bank`.`roles` (`id`, `r_name`, `dept_id`) VALUES ('23', 'Bookkeeper', '1');
INSERT INTO `bank`.`roles` (`id`, `r_name`, `dept_id`) VALUES ('24', 'Financial Manager', '2');